'use client';

import { Inter } from 'next/font/google';

import { PageInfoProvider } from '$containers/page-info.context';
import { TransitionProvider } from '$containers/transition.provider';
import { Layout } from '$layouts/layout/layout';

const inter = Inter({ subsets: ['latin'] });

import './globals.css';

// eslint-disable-next-line import/no-named-export
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="icon" type="image/png" href="/workout-planner.png" /> */}
      </head>
      <body className={inter.className}>
        <PageInfoProvider>
          <TransitionProvider>
            <Layout>{children}</Layout>
          </TransitionProvider>
        </PageInfoProvider>
      </body>
    </html>
  );
}
